name: ChronoCore
version: '${project.version}'
main: me.developer.chronocore.ChronoCore
api-version: '1.21'
author: xSnZX

commands:
  cc:
    description: to reload the Plugin ( Config.yml ) File.
  info:
    description: to show the plugin Info.
  timeleft:
    description: to show the player Time Left
